### ISSUE TITLE
Support for parse_mode field

### ISSUE THREAD

**Issue by hoplik** [afhacker/TelegramBotApi#2]
Hi! 
Can you add support for parse_mode field in API during send message (MarkdownV2 format needed)?

**Comment by amusleh-spotware-com** [comment]
Hi,
Sorry I can't, this package is a a fork of [Telegram.Bot](https://github.com/TelegramBots/Telegram.Bot).

We only use this for our popup package, I recommend to use the Telegram.Bot package instead.
